---
- name: copy minecraft functions
  template:
    src: functions.j2
    dest: "{{ minecraft_root_dir }}/functions"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0644

- name: create root tmux conf
  template:
    src: tmux.conf.j2
    dest: /root/.tmux.conf
    owner: root
    group: root
    mode: 0600

- name: copy minecraft-backup script
  template:
    src: minecraft-backup.j2
    dest: "{{ minecraft_root_dir }}/bin/minecraft-backup"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0755

- name: add backup cron
  cron:
    name: "minecraft full backup"
    special_time: "daily"
    job: "{{ minecraft_root_dir }}/bin/minecraft-backup full > {{ minecraft_root_dir }}/backup/full.log 2>&1"

- name: Accept minecraft eula
  template:
    src: eula.txt.j2
    dest: "{{ minecraft_root_dir }}/run/eula.txt"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0644

- name: set properties
  template:
    src: server.properties.j2
    dest: "{{ minecraft_root_dir }}/run/server.properties"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify: restart minecraft

- name: create ops.txt
  template:
    src: ops.txt.j2
    dest: "{{ minecraft_root_dir }}/run/ops.txt"
    owner: "{{ minecraft_user}}"
    group: "{{ minecraft_group }}"
    mode: 0644
  changed_when: false

- name: create minecraft defaults
  template:
    src: minecraft-defaults.sh.j2
    dest: /etc/default/minecraft
    owner: "{{ minecraft_user}}"
    group: "{{ minecraft_group }}"
    mode: 0644
  notify: restart minecraft
