name: Nginx
description: Create a server with either your own config or a basic backend config
imagePath: https://raw.github.com/clc-runner/Assets/master/ubuntu-logo112-200.png
shortDescription: Create an Nginx Server
version: 1.0
updateDate: May 9, 2016
public: false
defaultPlaybook: site.yml
author: Chaser
organization: Runner
organizationUrl: http://runner.ctl.io
fields:

  # ------------------------------------- #
  #                                       #
  # By default, the configuration will    #
  # use the default values. Modify        #
  # the following values, if you want to  #
  # change any of the parameters.         #
  #                                       #
  # ------------------------------------- #

  # ------------------------------------- #
  #                                       #
  # Server Parameters (not required)      #
  #                                       #
  # ------------------------------------- #

# Allow for multi-panel fact collection.
#panels:

  # - name: Server Location
  #   fields:

      # Data Center Name
    - name: datacenter_name
      displayName: Location
      type: datacenters
      required: false

    # Groups field.
    - name: server_group
      displayName: Group
      type: groups
      parent: datacenter_name
      required: false

    - name: server_count
      displayName: Number of Servers to Create
      type: slider
      required: true
      min: 1
      max: 100
      default: 1

    # Server Name
    - name: server_name
      displayName: Server Name
      type: text
      minLength: 1
      maxLength: 6

    # CPU Count
    - name: def_cpu
      displayName: server CPU
      type: slider
      required: true
      min: 1
      max: 16
      default: 1

    # Mem Count
    - name: def_mem
      displayName: server memory (GB)
      type: slider
      required: true
      min: 1
      max: 128
      default: 2

    - name: public
      displayName: PublicIP
      type: toggle
      default: false

    - name: listen_port
      displayName: Listen Port
      type: number
      minLength: 1
      maxLength: 65555

    - name: backend_group
      displayName: Backend Group
      type: text
      minLength: 1
      maxLength: 20

    - name: backend_port
      displayName: Backend Port
      type: number
      minLength: 1
      maxLength: 65555

tags:
  - proxy
  - nginx
  - webserver
