- name: Init the cluster if it hasnt been done so already
  shell: /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-init-user={{ couchbase_admin_username }} --cluster-init-password={{ couchbase_admin_password }} --cluster-init=8091 --cluster-init-ramsize={{ couchbase_server_ram }}
  when: ansible_ens160.ipv4.address == "{{ hostvars[groups['CouchBase'][0]]['ansible_ens160']['ipv4']['address'] }}"

- name: Add other nodes to the cluster
  shell: /opt/couchbase/bin/couchbase-cli server-add -c 127.0.0.1:8091 -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }} --server-add={{ hostvars[item]['ansible_ens160']['ipv4']['address'] }}:8091 --server-add-username={{ couchbase_admin_username }} --server-add-password={{ couchbase_admin_password }}
  when: ansible_ens160.ipv4.address == "{{ hostvars[groups['CouchBase'][0]]['ansible_ens160']['ipv4']['address'] }}"
  ignore_errors: true
  with_items: "{{ groups['CouchBase'] }}"

- name: Rebalance the cluster
  shell: /opt/couchbase/bin/couchbase-cli rebalance -c 127.0.0.1:8091 -u {{ couchbase_admin_username }} -p {{ couchbase_admin_password }}
  when: ansible_ens160.ipv4.address == "{{ hostvars[groups['CouchBase'][0]]['ansible_ens160']['ipv4']['address'] }}"
