name: Reboot Servers
description: Reboot some servers
shortDescription: Boot it
imagePath: http://www.sqlstad.nl/wp-content/uploads/2015/10/151008-reboot-300x169.jpg
updateDate: May 12, 2016
public: false
defaultPlaybook: server_reboot.yml
author: Chaser
organization: Runner
organizationUrl: http://runner.ctl.io
fields:
    - name: datacenter
      displayName: Location
      type: datacenters
      required: false

    - name: servers
      displayName: Servers
      type: servers
      parent: datacenter
      required: true
      multiple: true
      inventory: falseelmers89#
