- name: Reboot a server
  connection: local
  hosts: all
  tasks:
    - name: Server stop
      clc_server:
        server_ids: "{{ item }}"
        state: stopped
      with_items: '{{ groups.all }}'

    - name: Server start
      clc_server:
        server_ids: "{{ item }}"
        state: started
      with_items: '{{ groups.all }}'
