definitionUpdates: "false"
critical: "true"
security: "true"
servicePacks: "true"
updates: "false"
updateRollups: "false"
featurePacks: "false"
application: "false"
connectors: "false"
developerKits: "false"
tools: "false"
guidance: "false"
