name: RHEL HAProxy
description: Build a publicly accessible RHEL server with HAProxy and basic configuration. HAProxy configuration is setup to build a backend configuration based on a CLC Group Name. Frontend is default HTTP.
descriptionShort: RHEL with HAProxy
public: true
organization: CenturyLink
organizationUrl: https://runner.ctl.io
author: Runner Team

# Allow for single panel fact collection.
fields:

  # Sample text field
  - name: server_group
    displayName: Server Group
    type: text
    required: true
    
  - name: backend_group
    displayName: Backend Group
    type: text
    required: true

  # Sample password field
  - name: serverpass
    displayName: Root Password
    type: password
    required: true

tags:
  - cloud
  - loadbalancing
  - rhel
