- name: Perform Definition Updates
  win_updates:
    category_names: "DefinitionUpdates"
    log_path: c:/definition_updates.txt
  register: definintion

- name: Reboot server if required
  hosts: localhost
  connection: local
  clc_server:
    server_ids: "{{ }}"
    state: stopped
  when: ("{{ definintion.reboot_required }}" == 'true')

- name: Reboot server if required
  hosts: localhost
  connection: local
  clc_server:
    server_ids: "{{ }}"
    state: started
  when: ("{{ definintion.reboot_required }}" == 'true')
