- name: Update Guidance Libraries
  win_updates:
    category_names: "Guidance"
    log_path: c:/guidance_updates.txt
  register: guidance

- name: Reboot server if required
  hosts: localhost
  connection: local
  clc_server:
    server_ids: "{{ }}"
    state: stopped
  when: ("{{ guidance.reboot_required }}" == 'true')

- name: Reboot server if required
  hosts: localhost
  connection: local
  clc_server:
    server_ids: "{{ }}"
    state: started
  when: ("{{ guidance.reboot_required }}" == 'true')
