---
- include: definition.yml
  when: ("{{ definitionUpdates }}" == 'true')

- include: criticals.yml
  when: ("{{ critical }}" == 'true')

- include: security.yml
  when: ("{{ security }}" == 'true')

- include: service_packs.yml
  when: ("{{ servicePacks }}" == 'true')

- include: general_updates.yml
  when: ("{{ updates }}" == 'true')

- include: rollups.yml
  when: ("{{ updateRollups }}" == 'true')

- include: feature_packs.yml
  when: ("{{ featurePacks }}" == 'true')

- include: application.yml
  when: ("{{ application }}" == 'true')

- include: connectors.yml
  when: ("{{ connectors }}" == 'true')

- include: dev_kits.yml
  when: ("{{ developerKits }}" == 'true')

- include: tools.yml
  when: ("{{ tools }}" == 'true')

- include: guidance.yml
  when: ("{{ guidance }}" == 'true')
