- name: Reboot server if required
  hosts: localhost
  connection: local
  clc_server:
    server_ids: "{{ item }}"
    state: stopped
  with_items: groups.server

- name: Reboot server if required
  hosts: localhost
  connection: local
  clc_server:
    server_ids: "{{ item }}"
    state: started
  with_items: groups.server
