- name: Apply Security Updates
  win_updates:
    category_names: "SecurityUpdates"
    log_path: c:/security_updates.txt
  register: security

- name: Reboot server if required
  hosts: localhost
  connection: local
  clc_server:
    server_ids: "{{ }}"
    state: stopped
  when: ("{{ security.reboot_required }}" == 'true')

- name: Reboot server if required
  hosts: localhost
  connection: local
  clc_server:
    server_ids: "{{ }}"
    state: started
  when: ("{{ security.reboot_required }}" == 'true')
