---
- name: sample test playbook
  hosts: all 
  vars:
    vars_file: my_vars.yml
  tasks:
    - name: Say something
      debug: msg="I have started..."
    - name: Include something
      include: file1.yml
