name: Password Strength Test Product
description: This is the description of the password strength test product
shortDescription: This is the short description of the password strength test product
imagePath: https://i.imgur.com/WjuS4XX.png
version: 3.4.5
updateDate: Jan 1, 2016
public: false

# Allow for single panel fact collection.
fields:

  # Password Strength field.
  - name: password_strength_test
    displayName: Password Strength Test
    validationMsg: Password Strength Validation Message
    requiredStrength: 4
    dissallowedCharacters: []{}
    type: passwordStrength
    required: true

tags:
  - cloud
  - storage
  - block
  - seph
