name: Kubernetes Clustered App Suite
description: Kubernetes Clustered Environment with Wordpress, Jenkins, RocketChat, Drupal, and More!
descriptionShort: Kubernetes Clustered Environment with Wordpress, Jenkins, RocketChat, Drupal, and More!
imagePath: http://info.runner.ctl.io/wp-content/uploads/2016/04/Kubernetes-1.png
shortDescription: Kubernetes Clustered Environment with Wordpress, Jenkins, RocketChat, Drupal, and More!
version: 1.0
updateDate: April 6, 2016
public: true
defaultPlaybook: kubernetes-full-plus-apps.yml
author: Chris Kent
organization: CenturyLink
organizationUrl: http://runner.ctl.io

fields:

  # Data Center field.
  - name: datacenter
    displayName: Datacenter
    type: datacenters
    required: true

  # Networks field.
  - name: network_id
    displayName: Network
    type: networks
    parent: datacenter
    required: true

  # Group field.
  - name: group
    displayName: Group
    type: text
    required: true

tags:
  - blogging
  - wordpress
  - social
