- hosts: master
  tasks:
  - name: Create Wordpress Replication Controller.
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: ReplicationController
        metadata:
          name: "wordpress-rc"
          namespace: default
        spec:
          replicas: 1
          imagePullPolicy: IfNotPresent
          selector:
            app: "wordpress"
          template:
            metadata:
              labels:
                app: "wordpress"
            spec:
              containers:
              - name: "mariadb"
                image: mariadb:5
                env:
                - name: MYSQL_ROOT_PASSWORD
                  value: password
                ports:
                - containerPort: 3306
              - name: "wordpress"
                image: wordpress
                env:
                - name: WORDPRESS_DB_HOST
                  value: 127.0.0.1
                - name: WORDPRESS_DB_PASSWORD
                  value: password
                ports:
                - containerPort: 80
            restartPolicy: Always
            
  - name: Create Wordpress Service
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: Service
        metadata:
          name: "wordpress-svc"
          namespace: default
          labels:
            app: "wordpress"
        spec:
          type: NodePort
          ports:
          - port: 8080
            targetPort: 80
            protocol: TCP
            nodePort: 30080
          selector:
            app: "wordpress"