- hosts: localhost
  tasks:
  
  - name: Add Master To Inventory
    add_host:
      name=UC1WFADK8SM16
      ansible_ssh_host=10.120.45.15
      ansible_ssh_user=root
      ansible_ssh_pass=CDtqzVKdkUV8Aiq9w/RV
      groups=master
      
  - name: Add Node To Inventory
    add_host:
      name=UC1WFADK8SN45
      ansible_ssh_host=10.120.45.16
      ansible_ssh_user=root
      ansible_ssh_pass=CDtqzVKdkUV8Aiq9w/RV
      etcd_endpoint=http://10.120.45.15:4001 
      apiserver_endpoint=http://10.120.45.15:8080
      groups=node

- include: kubernetes-master.yml
- include: kubernetes-node.yml
- include: kubernetes-app-wordpress.yml
- include: kubernetes-app-rocket-chat.yml
- include: kubernetes-app-ghost.yml
- include: kubernetes-app-jenkins.yml
- include: kubernetes-app-joomla.yml
- include: kubernetes-app-mysql.yml
