- hosts: master
  tasks:
  - name: Create Jenkins Replication Controller.
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: ReplicationController
        metadata:
          name: "jenkins-rc"
          namespace: default
        spec:
          replicas: 1
          imagePullPolicy: IfNotPresent
          selector:
            app: "jenkins"
          template:
            metadata:
              labels:
                app: "jenkins"
            spec:
              containers:
              - name: "jenkins"
                image: jenkins
                ports:
                - containerPort: 8080
            restartPolicy: Always
            
  - name: Create Jenkins Service
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: Service
        metadata:
          name: "jenkins-svc"
          namespace: default
          labels:
            app: "jenkins"
        spec:
          type: NodePort
          ports:
          - port: 8080
            targetPort: 8080
            protocol: TCP
            nodePort: 30380
          selector:
            app: "jenkins"