- hosts: master
  tasks:
  - name: Create mysql Replication Controller.
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: ReplicationController
        metadata:
          name: "mysql-rc"
          namespace: default
        spec:
          replicas: 1
          imagePullPolicy: IfNotPresent
          selector:
            app: "mysql"
          template:
            metadata:
              labels:
                app: "mysql"
            spec:
              containers:
              - name: "mysql"
                image: mysql
                env:
                - name: MYSQL_ROOT_PASSWORD
                  value: password
                ports:
                - containerPort: 3306
            restartPolicy: Always
            
  - name: Create mysql Service
    kubernetes:
      endpoint: "{{ apiserver_endpoint }}"
      state: present
      model:
        apiVersion: v1
        kind: Service
        metadata:
          name: "mysql-svc"
          namespace: default
          labels:
            app: "mysql"
        spec:
          type: NodePort
          ports:
          - port: 3306
            targetPort: 3306
            protocol: TCP
            nodePort: 30306
          selector:
            app: "mysql"