name: Ansible Windows Preparation
shortDescription: Prepare Windows servers for Ansible execution
Description: In order to facilitate the use of Ansible with Windows, WinRM and PowerShell 3 need to be configured.
version: 1.0.0
updateDate: May 15, 2016
public: true
defaultPlaybook:
author: Chaser
organization: Runner
organizationUrl: http://ctl.io/runner

fields:

  - name: datacenter
    displayName: location
    type: datacenters
    required: true

  - name: server
    displayName: Servers
    type: server
    required: true
    parent: datacenter
