name: Ansible Windows Preparation
description: In order to facilitate the use of Ansible with Windows, WinRM and PowerShell 3 need to be configured.
shortDescription: Prepare Windows servers for Ansible execution
imagePath: http://www.factfiend.com/wp-content/uploads/2014/10/windows-logo.png
version: 1.0.0
updateDate: May 18, 2016
public: true
defaultPlaybook: windows_configure.yml
author: Runner Team
organization: Runner
organizationUrl: http://ctl.io/runner

fields:

  - name: datacenter
    displayName: location
    type: datacenters
    required: true

  - name: server
    displayName: Servers
    type: servers
    multiple: true
    required: true
    parent: datacenter
