- name: CLC | Create Nginx Group
  clc_group:
    name: "{{ group_name }}"
    location: "{{ datacenter }}"
    state: present

- name: Generate Password
  command: openssl rand -base64 15
  register: serverpass
  changed_when: False

- name: CLC | Build Nginx Server if Needed
  clc_server:
    name: "{{ server_name }}"
    location: "{{ datacenter }}"
    template: "{{ os_template }}"
    password: "{{ serverpass.stdout }}"
    exact_count: "{{ server_count }}"
    group: "{{ group_name }}"
    count_group: "{{ group_name }}"
    cpu: "{{ cpu }}"
    memory: "{{ memory }}"
    type: "{{ type }}"
    storage_type: "{{ storage_type }}"
  register: nginx

- name: CLC | Add public ipaddress
  clc_publicip:
    server_ids: "{{ item.name }}"
    ports:
      - "{{ listen_port }}"
    protocol: TCP
    state: present
  with_items: "{{nginx.servers}}"
  when: ("{{ public }}" == 'true')

- name: Wait for SSH Services to Become Available
  command: sleep 15

- name: Add New Servers to an inventory
  add_host:
    name={{ item.name }}
    ansible_ssh_host={{ item.ipaddress }}
    ansible_ssh_user=root
    ansible_ssh_pass={{ serverpass.stdout }}
    groupname=nginx
  with_items: "{{ nginx.servers }}"
