name: WordPress
description: Most popular blogging software WordPress can be built in your CenturyLink cloud within minutes. WordPress is most extensively used software to host blogs and even applications. With the high contribution by open source community, it provides a wide range of free themes and plugins to suit your blog or app and can help you host your business pretty quickly. <a href="https://wordpress.org/" target="_blank">Know more about WordPress.</a>
descriptionShort: Most popular blogging software WordPress can be built in your CenturyLink cloud within minutes.</a>
imagePath: https://s.w.org/style/images/wp-header-logo.png?1
shortDescription: Install and Configure WordPress on a New Ubuntu Server
version: 1.2.3
updateDate: Jan 1, 2016
public: true
defaultPlaybook: playbook.yml
author: Chris Kent
organization: CenturyLink
organizationUrl: http://runner.ctl.io

# Allow for single panel fact collection.
fields:

  # ------------------------------------- #
  #                                       #
  # By default, the configuration will    #
  # use the default values. Modify        #
  # the following values, if you want to  #
  # change any of the parameters.         #
  #                                       #
  # ------------------------------------- #

  # ------------------------------------- #
  #                                       #
  # Server Parameters (not required)      #
  #                                       #
  # ------------------------------------- #

  # Server Password
  - name: pswd
    displayName: Server Password
    type: password
    minLength: 1
    maxLength: 35

  # Server Name
  - name: server_name
    displayName: Server Name
    type: text
    minLength: 1
    maxLength: 6

  # Server Count
  - name: server_count
    displayName: Server Count
    type: number
    minLength: 1
    maxLength: 5

  # Datacenter Name
  - name: datacenter_name
    displayName: Datacenter
    type: text
    minLength: 2
    maxLength: 4

  # CPU Count
  - name: def_cpu
    displayName: CPU Count
    type: number
    minLength: 1
    maxLength: 3

  # Mem Count
  - name: def_mem
    displayName: Memory Count
    type: number
    minLength: 1
    maxLength: 3





  # ------------------------------------- #
  #                                       #
  # MySQL Parameters (not required)       #
  #                                       #
  # ------------------------------------- #

  # MySQL Root Password
  - name: mysql_root_pass
    displayName: MySQL Root Password
    type: password
    minLength: 1
    maxLength: 35

  # Sample numeric field
  - name: mysql_port
    displayName: MySQL Port
    type: number
    min: 1
    max: 8


  # Sample numeric field
  - name: mysql_bind_address
    displayName: MySQL Bind Address
    type: text
    min: 1
    max: 20


  # ------------------------------------- #
  #                                       #
  # Wordpress Parameters                  #
  #                                       #
  # ------------------------------------- #

  # Default WordPress Site Name
  - name: website_name
    displayName: WordPress Site Name
    type: text
    minLength: 1
    maxLength: 150

  # WordPress Directory to Install In
  - name: wordpress_dir
    displayName: WordPress Install Directory
    type: text
    minLength: 1
    maxLength: 250

  # Domain/URL for WordPress
  - name: wordpress_url
    displayName: WordPress URL
    type: text
    minLength: 1
    maxLength: 35

  # WordPress Username
  - name: wordpress_user
    displayName: WordPress Username
    type: text
    minLength: 1
    maxLength: 35

  # WordPress Password
  - name: wordpress_passwd
    displayName: WordPress Password
    type: password
    minLength: 1
    maxLength: 35

  # WordPress Database Name
  - name: wordpress_db
    displayName: Wordpress Database Name
    type: text
    minLength: 1
    maxLength: 35


tags:
  - blogging
  - wordpress
  - social
