- name: "Build {{ server_name }} Servers | Exact Count of {{ server_count }}"
  clc_server:
    name: "{{ server_name }}"
    location: "{{ datacenter }}"
    template: "{{ server_template }}"
    password: "{{ serverpass.stdout }}"
    group: "{{ server_group }}"
    exact_count: "{{ server_count }}"
    count_group: "{{ server_group }}"
    network_id: "{{ network_id }}"
    cpu: "{{ cpu_count }}"
    memory: "{{ memory_count }}"
    type: "{{ type }}"
    storage_type: "{{ storage_type }}"
    additional_disks: "{{ additional_disks }}"
  register: provisioned
