---
- name: Generate Server Admin Password
  command: openssl rand -base64 15
  register: serverpass
  changed_when: False

- name: Create Server Group
  clc_group:
    name: "{{ server_group }}"
    location: "{{ datacenter }}"
    state: present
  when: build_type is defined

- include: "{{ build_type }}.yml"

- name: Wait for SSH Services to Become Available
  command: sleep 15

- name: "Add {{ server_name }} Servers to an in-memory Group"
  add_host:
    name={{ item.name }}
    ansible_ssh_host={{ item.ipaddress }}
    ansible_ssh_user=root
    ansible_ssh_pass={{ serverpass.stdout }}
    groupname=CouchBase
  with_flattened: '{{ provisioned.servers }}'
