- name: Add kube-apiserver service configuration.
  template: src=kube-apiserver.conf.j2 dest=/etc/init/kube-apiserver.conf

- name: Enable kube-apiserver service.
  service: name=kube-apiserver enabled=yes

- name: Start kube-apiserver service.
  service: name=kube-apiserver state=restarted
  
- name: Add kube-controller-manager service configuration.
  template: src=kube-controller-manager.conf.j2 dest=/etc/init/kube-controller-manager.conf

- name: Enable kube-controller-manager service.
  service: name=kube-controller-manager enabled=yes

- name: Start kube-controller-manager service.
  service: name=kube-controller-manager state=restarted
  
- name: Add kube-scheduler service configuration.
  template: src=kube-scheduler.conf.j2 dest=/etc/init/kube-scheduler.conf

- name: Enable kube-scheduler service.
  service: name=kube-scheduler enabled=yes

- name: Start kube-scheduler service.
  service: name=kube-scheduler state=restarted
  
- name: Install httplib2.
  apt: name=python-httplib2 state=present
  
