name: Super Cool Product Name
description: This is the description of the super cool product
descriptionShort: This is the short description of the super cool product
imagePath: https://i.imgur.com/x2KufBj.png
version: 1.2.3
updateDate: Jan 1, 2016
public: false

# Allow for single panel fact collection.
fields:

  - name: groups_multiple
    displayName: Groups
    type: groups
    required: true
    multiple: true
    
  # Servers field.
  - name: groups_single
    displayName: Groups Single
    type: groups
    required: true
    multiple: false

  # Servers field.
  - name: servers_multiple
    displayName: Servers (Add To Inventory)
    type: servers
    required: true
    multiple: true
    inventory: true
    
  # Servers field.
  - name: servers_single
    displayName: Servers Single (Add To Inventory)
    type: servers
    required: true
    multiple: false
    inventory: true
    
  # Servers field.
  - name: servers_multiple_props
    displayName: Servers (Add To Properties)
    type: servers
    required: true
    multiple: true
    inventory: false
    
  # Servers field.
  - name: servers_single_props
    displayName: Servers Single (Add To Properties)
    type: servers
    required: true
    multiple: false
    inventory: false

  # Sample text field
  - name: instance_name
    displayName: Instance Name
    type: text
    required: true
    minLength: 1
    maxLength: 35
  
  # Sample password field
  - name: root_password
    displayName: Root Password
    type: password
    required: true
    
  # Sample numeric field
  - name: node_count
    displayName: Cluster Nodes
    type: number
    required: true
    min: 6
    max: 99

  # Sample text area field
  - name: license
    displayName: License
    type: textarea
    required: true
    
  # Sample network, should load networks based on account alias.
  - name: selectName
    displayName: Select Display Name
    type: select
    required: true
    options:
      - displayName: displayNameOne
        value: optionValueOne
      - displayName: displayNameTwo
        value: optionValueTwo
        selected: true
      - displayName: displayNameThree
        value: optionValueThree
        
  - name: multiSelectName
    displayName: Multi-Select Display Name
    type: select
    required: true
    multiple: true
    options:
      - displayName: displayNameOne
        value: optionValueOne
      - displayName: displayNameTwo
        value: optionValueTwo
        selected: true
      - displayName: displayNameThree
        value: optionValueThree

tags:
  - cloud
  - storage
  - block
  - seph
