- name: Add etcd service configuration.
  template: src=etcd.conf.j2 dest=/etc/init/etcd.conf

- name: Enable etcd service.
  service: name=etcd enabled=yes

- name: Start etcd service.
  service: name=etcd state=restarted