name: VM Snapshot
description: Create a snapshot of your VMs with ease.
imagePath: https://raw.githubusercontent.com/clc-runner/Assets/master/snapshot.jpg
shortDescription: Create a snapshot of your VMs.  Schedule them to automate it!
version: 1.1.0
updateDate: October 4, 2016
public: true
defaultPlaybook: playbook.yml
author: Chris Kent
organization: CenturyLink
organizationUrl: http://ctl.io/runner
schedulable: true

# Allow for single panel fact collection.
fields:

  # ------------------------------------- #
  #                                       #
  # By default, the configuration will    #
  # use the default values. Modify        #
  # the following values, if you want to  #
  # change any of the parameters.         #
  #                                       #
  # ------------------------------------- #

  # Data Center field.
  - name: datacenter
    displayName: Datacenter Picker
    type: datacenters
    required: false

  # Groups field.
  - name: server_group
    displayName: Group Picker
    type: groups
    parent: datacenter
    multiple: true
    required: false

 # Text Block Info
  - name: text_block_info
    type: textblock
    level: info
    title: "Runner Tip"
    text: "Did you know it's easy to setup groups and then create snapshots of all of the VMs in that group? You don't have to worry about manually adding or removing VMs as they're created.  It's automatic."


  # Servers field.
  - name: servers_multiple
    displayName: OR Select Servers
    type: servers
    required: false
    multiple: true
    inventory: false


  # Toggle field.
  - name: server_list_toggle
    displayName: Use Server List
    type: toggle
    default: true
    required: false

  # Text Block Danger
  - name: text_block_danger
    type: textblock
    level: warning
    title: Inventory Selection
    text: You can select server groups OR select individual servers. Combinations are not allowed at this time.



  # Sample slider field
  - name: slider_ttl
    displayName: Days to Keep Snapshot
    type: slider
    required: true
    min: 1
    max: 10
    default: 5

  - name: ignore_failures
    displayName: Ignore Failures?
    type: toggle
    default: false
    required: false

  - name: text_block_warning
    type: textblock
    level: warning
    title: "Ignore Failures"
    text: "Setting ignore failures to yes will allow your job to continue if one or more servers fails to snapshot. A list of failed servers will be printed at the end of your job regardless."


tags:
- ops
- snapshot
- server
- backup
- copy
- clc
- centurylink
- save
