# Copyright 2015 CenturyLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Create VM Snapshot
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    expiration_days: 1
    ignore_failures: "false"

  tasks:

    - name: Get group servers
      clc_group_fact:
        group_id: "{{server_group}}"
      register: server_group_list
      when: "{{ server_list_toggle }} == false"

    - name: Remove group snapshots if present
      clc_server_snapshot:
        server_ids: "{{server_group_list.group.servers}}"
        expiration_days: "{{slider_ttl}}"
        wait: True
        state: absent
      when: "{{ server_list_toggle }} == false"

    - name: Create server snapshot with groups
      clc_server_snapshot:
        server_ids: "{{server_group_list.group.servers}}"
        expiration_days: "{{slider_ttl}}"
        wait: True
        ignore_failures: true
        state: present
      when: "{{ server_list_toggle }} == false"
      register: failures_group

    - name: Remove server snapshot if present
      clc_server_snapshot:
        server_ids: "{{servers_multiple}}"
        expiration_days: "{{slider_ttl}}"
        wait: True
        state: absent
      when: "{{ server_list_toggle }}"

    - name: Create server snapshot with list
      clc_server_snapshot:
        server_ids: "{{servers_multiple}}"
        expiration_days: "{{slider_ttl}}"
        wait: True
        ignore_failures: true
        state: present
      when: "{{ server_list_toggle }}"
      register: failures_servers

    - name: Print Failed Servers if applicable
      debug: msg="These servers failed to snapshot {{ failures_servers.failed_server_ids }}"
      when: failures_servers.failed_server_ids is defined and failures_servers.failed_server_ids|length > 0 and ignore_failures == "true"

    - name: Print Failed Servers if applicable
      debug: msg="These servers failed to snapshot {{ failures_group.failed_server_ids }}"
      when: failures_group.failed_server_ids is defined and failures_group.failed_server_ids|length > 0 and ignore_failures == "true"

    - name: Fail Execution if applicable
      fail: msg="These servers failed to snapshot {{ failures_servers.failed_server_ids }}"
      when: failures_servers.failed_server_ids is defined and failures_servers.failed_server_ids|length > 0 and ignore_failures == "false"

    - name: Fail Execution if applicable
      fail: msg="These servers failed to snapshot {{ failures_group.failed_server_ids }}"
      when: failures_group.failed_server_ids is defined and failures_group.failed_server_ids|length > 0 and ignore_failures == "false"
