name: group_test
description: shows a bug
shortDescription: shows a bug
updateDate: May 9, 2016
public: false
defaultPlaybook: site.yml
author: Chaser
organization: Runner
organizationUrl: http://runner.ctl.io
fields:

  # ------------------------------------- #
  #                                       #
  # By default, the configuration will    #
  # use the default values. Modify        #
  # the following values, if you want to  #
  # change any of the parameters.         #
  #                                       #
  # ------------------------------------- #

  # ------------------------------------- #
  #                                       #
  # Server Parameters (not required)      #
  #                                       #
  # ------------------------------------- #

# Allow for multi-panel fact collection.
#panels:
    - name: datacenter_name
      displayName: datacenter
      type: datacenters
      required: true

    # Groups field.
    - name: server_group
      displayName: Server Group
      type: groups
      parent: datacenter_name
      required: false

    - name: backend_group
      displayName: Backend Group
      type: groups
      parent: datacenter_name
      required: false


tags:
  - proxy
  - nginx
  - webserver

requirements:
  - clc-ansible-module==1.1.11
  
