name: CouchBase
description: Couchbase Server is an open-source, distributed (shared-nothing architecture) multi-model NoSQL document-oriented database software package that is optimized for interactive applications.
shortDescription: 3 node CouchBase Cluster
version: 1.0
defaultPlaybook: site.yml
author: Runner
organization: Runner
organizationUrl: http://runner.ctl.io
imagePath: https://raw.githubusercontent.com/docker-library/docs/00543c65b06a7f8f54aa4f7908f7d91705d8ddec/couchbase/logo.png
public: false

fields:
  - name: datacenter
    displayName: Location
    type: datacenters
    required: true
    default: UC1

  - name: network_id
    displayName: Network
    type: networks
    parent: datacenter
    required: true

  - name: cpu_count
    displayName: CPU
    type: slider
    required: false
    min: 1
    max: 35
    default: 4

  - name: memory_count
    displayName: Memory
    type: slider
    required: false
    min: 1
    max: 128
    default: 16

# optional couchbase installation stuff...pretty important

  - name: couchbase_enterprise
    displayName: Enterprise Edition
    type: toggle
    default: false

  - name: couchbase_admin_username
    type: text
    default: Administrator
    required: false
    minLength: 6
    maxLength: 20

  - name: couchbase_admin_password
    type: password
    required: true
    min: 6
    max: 20
