name: CouchBase
description: Couchbase Server is an open-source, distributed (shared-nothing architecture) multi-model NoSQL document-oriented database software package that is optimized for interactive applications.
shortDescription: Couchbase NoSQL Database
version: 4.0.0-4051
defaultPlaybook: site.yml
author: Runner
organization: Runner
organizationUrl: http://runner.ctl.io
imagePath: https://raw.githubusercontent.com/docker-library/docs/00543c65b06a7f8f54aa4f7908f7d91705d8ddec/couchbase/logo.png
public: true

fields:
  - name: datacenter
    displayName: Location
    type: datacenters
    required: true
    default: UC1

  - name: network_id
    displayName: Network
    type: networks
    parent: datacenter
    required: true

  - name: server_count
    displayName: Server Count
    type: slider
    required: false
    min: 3
    max: 10
    default: 3

  - name: cpu_count
    displayName: CPU
    type: slider
    required: false
    min: 1
    max: 35
    default: 4

  - name: memory_count
    displayName: Memory
    type: slider
    required: false
    min: 4
    max: 128
    default: 16

# optional couchbase installation stuff...pretty important

#  - name: couchbase_enterprise
#    displayName: Enterprise Edition
#    type: toggle
#    required: true
#    default: false

  - name: couchbase_admin_username
    type: text
    default: Administrator
    required: false
    minLength: 6
    maxLength: 20

  - name: couchbase_admin_password
    displayName: CouchBase Admin Password
    validationMsg: Password Validation
    requiredStrength: 4
    type: passwordStrength
    required: true

#  - name: clustered
#    displayName: Clustered
#    type: toggle
#    required: true
#    default: true
