---
- name: Create nginx group
  group:
    name: nginx

- name: Create nginx user
  user:
    name: nginx

- name: Install nginx
  apt:
    name: nginx

- name: Set nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: "{{ nginx_owner }}"
    group: "{{ nginx_group }}"

- name: Get backend group information
  clc_server_fact:
    server_id: "{{ item }}"
  with_items:
    - "{{ backend_servers }}"
  register: backend

- name: Set backend config
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
    owner: "{{ nginx_owner }}"
    group: "{{ nginx_group }}"
  notify: restart nginx

- name: Start / enable nginx
  service:
    name: nginx
    state: started
